server:
  port: 8201
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/sakila?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: peter
    password: abc123_
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.macro.cloud.user.domain
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
